/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.7.0
 *
 * Project: 'inferencing.Speed+CM85' 
 * Target:  'Speed+CM85' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "ARMCM85.h"



#endif /* RTE_COMPONENTS_H */
